# Generated by Django 4.2.11 on 2024-04-01 12:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="current_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="текущий участник",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="count_of_members",
            field=models.IntegerField(
                default=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="количество участников",
            ),
        ),
    ]
