# Generated by Django 4.2.11 on 2024-04-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_vacancy_current_member_alter_team_count_of_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
    ]
