name: Deployment

on:
  workflow_run:
    workflows: ["Django CI/CD", "Frontend CI/CD"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v3
      - name: Pull Docker images and start containers
        run: |
          docker-compose up -d --build
