name: Frontend CI/CD

on:
    workflow_run:
      workflows: ["Django CI/CD"]
      types:
        - completed

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd frontend && npm install
      - name: Linting
        run: cd frontend && npm run lint
        continue-on-error: true

  test_build:
    runs-on: ubuntu-latest
    needs: linting

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t skillhub-backend frontend/
